<?php
function title_case_menu(){
    $items = array();
    $items['title_case'] = array(
        'title' => 'Title Case',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('title_case_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['title_success'] = array(
        'title' => "Title Case Success",
        'page callback' => "title_case_success",
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function title_case_form() {
    $form['convert_case'] = array(
        '#title' => 'Convert your cases',
        '#type' => 'textfield',
        '#description' => t('please enter the title you want translated into title case'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
    return $form;
}

    function title_case_form_submit($form, &$form_state) {
        $exceptions = ["a", "an", "the", "is", "or", "to", "and", "but", "for", "nor", "on", "of"];
        $title = $form_state['values']['convert_case'];
        $split = explode(" ", $title);
        $words = array();

        foreach ($split as $i=>$value) {
            if(in_array($value, $exceptions) && $i != 0){
                $array = strtolower($value);
            }
            else{
                $lowercase = strtolower($value);
                $array = ucfirst($lowercase);
            }
            array_push($words, $array);
        }
        $output = implode(" ", $words);


        //foreach($title)
        $_SESSION['title_case_output'] = $output;

        $form_state['redirect'] = 'title_success';
    }

    function title_case_success() {
        $result = $_SESSION['title_case_output'];
        return "$result";
    }
